
deployment:
  version: apps/v1
  secret: gitlab
  name: checkoutservice
  label: checkoutservice
  replicas: 2

containers:
- name: helloworld
  port: 8080
  image: registry.gitlab.com/pdustdar/online-boutique/checkoutservice:0.0.1
  env:
    hasenv: true
    vars:
      - name: DISABLE_STATS
        value: "1"
      - name: DISABLE_TRACING
        value: "1"
      - name: DISABLE_PROFILER
        value: "1"
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice.ns-alireza.svc.cluster.local:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice.ns-alireza.svc.cluster.local:8080"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice.ns-alireza.svc.cluster.local:8080"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice.ns-alireza.svc.cluster.local:8080"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice.ns-alireza.svc.cluster.local:8080"
      - name: CART_SERVICE_ADDR
        value: "cartservice.ns-alireza.svc.cluster.local:7070"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  probes:
    liveness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:8080
      - -rpc-timeout=5s
      delay: 10
      period: 10
    readiness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:8080
      - -rpc-timeout=5s
      delay: 10
      period: 10

service:
  version: v1
  type: ClusterIP
  name: checkoutservice
  ports: 
  - port: 8080
    targetPort: 8080

