
deployment:
  version: apps/v1
  secret: gitlab
  name: currencyservice
  label: currencyservice
  replicas: 2

containers:
- name: currencyservice
  port: 8080
  image: registry.gitlab.com/pdustdar/online-boutique/currencyservice:0.0.1
  env:
    hasenv: true
    vars:
      - name: DISABLE_STATS
        value: "1"
      - name: DISABLE_TRACING
        value: "1"
      - name: DISABLE_PROFILER
        value: "1"
      - name: PORT
        value: "8080"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  probes:
    liveness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=localhost:8080
      - -rpc-timeout=10s
      delay: 10
      period: 10
    readiness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=localhost:8080
      - -rpc-timeout=10s
      delay: 10
      period: 10

service:
  version: v1
  type: ClusterIP
  name: currencyservice
  ports: 
  - port: 8080
    targetPort: 8080

