
deployment:
  version: apps/v1
  secret: regcred
  name: helloworld
  label: helloworld

containers:
- name: helloworld
  port: 8080
  replicas: 2
  image: registry.hamdocker.ir/alirezaamd3/helloworld:latest
  env:
    has-env: true
    vars:
      - name: RAND_SVC_HOST
        value: randomstring
      - name: RAND_SVC_PORT
        value: "8200"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  probes:
    liveness:
      has-probe: true
      type: http
      path: /_healthz
      has-header: true
      headers:
      - name: shop_session-id
        value: x-liveness-probe
      delay: 10
      period: 5
    readiness:
      has-probe: true
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:80
      - -rpc-timeout=5s
      delay: 30
      period: 5

service:
  version: v1
  type: ClusterIP
  name: helloworld-service
  ports: 
  - port: 80
    targetPort: 8080

