
deployment:
  version: apps/v1
  secret: gitlab
  name: emailservice
  label: emailservice
  replicas: 2

containers:
- name: emailservice
  port: 8080
  image: registry.gitlab.com/pdustdar/online-boutique/emailservice:0.0.1
  env:
    hasenv: true
    vars:
      - name: DISABLE_STATS
        value: "1"
      - name: DISABLE_TRACING
        value: "1"
      - name: DISABLE_PROFILER
        value: "1"
      - name: PORT
        value: "8080"
  resources:
    requests:
      memory: "180Mi"
      cpu: "200m"
    limits:
      memory: "300Mi"
      cpu: "300m"
  probes:
    liveness:
      hasprobe: true
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=localhost:8080
      - -rpc-timeout=10s
      delay: 30
      period: 15
      timeout: 11
    readiness:
      hasprobe: true
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=localhost:8080
      - -rpc-timeout=10s
      delay: 30
      period: 15
      timeout: 11

service:
  version: v1
  type: ClusterIP
  name: emailservice
  ports: 
  - port: 8080
    targetPort: 8080

