
deployment:
  version: apps/v1
  secret: gitlab
  name: cartservice
  label: cartservice
  replicas: 2

containers:
- name: cartservice
  port: 7070
  image: registry.gitlab.com/pdustdar/online-boutique/cartservice:0.0.1
  env:
    hasenv: true
    vars:
      - name: DISABLE_STATS
        value: "1"
      - name: DISABLE_TRACING
        value: "1"
      - name: DISABLE_PROFILER
        value: "1"
      - name: REDIS_ADDR
        value: "cartservice-redis-master.ns-alireza.svc.cluster.local:6379"
  resources:
    requests:
      memory: "180Mi"
      cpu: "200m"
    limits:
      memory: "300Mi"
      cpu: "300m"
  probes:
    liveness:
      hasprobe: true
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:7070
      - -rpc-timeout=10s
      delay: 30
      period: 15
      timeout: 11
    readiness:
      hasprobe: true
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:7070
      - -rpc-timeout=10s
      delay: 30
      period: 15
      timeout: 11

service:
  version: v1
  type: ClusterIP
  name: cartservice
  ports: 
  - port: 7070
    targetPort: 7070

