
deployment:
  version: apps/v1
  secret: gitlab
  name: cartservice
  label: cartservice
  replicas: 2

containers:
- name: cartservice
  port: 8080
  image: registry.gitlab.com/pdustdar/online-boutique/cartservice:0.0.1
  env:
    hasenv: true
    vars:
      - name: DISABLE_STATS
        value: "1"
      - name: DISABLE_TRACING
        value: "1"
      - name: DISABLE_PROFILER
        value: "1"
      - name: REDIS_ADDR
        value: "cartservice-redis-master.ns-alireza.svc.cluster.local:6379"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  probes:
    liveness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:8080
      - -rpc-timeout=5s
      delay: 10
      period: 10
    readiness:
      hasprobe: false
      type: shell
      command:
      - /bin/grpc_health_probe
      - -addr=:8080
      - -rpc-timeout=5s
      delay: 10
      period: 10

service:
  version: v1
  type: ClusterIP
  name: cartservice
  ports: 
  - port: 8080
    targetPort: 8080

