
deployment:
  version: apps/v1
  secret: gitlab
  name: loadgenerator
  label: loadgenerator
  replicas: 1

containers:
- name: loadgenerator
  port: 8080
  image: registry.gitlab.com/pdustdar/online-boutique/loadgenerator:0.0.1
  env:
    hasenv: true
    vars:
      - name: USERS
        value: "10"
      - name: FRONTEND_ADDR
        value: "frontend.ns-alireza.svc.cluster.local:8080"
  resources:
    requests:
      memory: "180Mi"
      cpu: "200m"
    limits:
      memory: "300Mi"
      cpu: "300m"
  probes:
    liveness:
      hasprobe: false
    readiness:
      hasprobe: false

service:
  version: v1
  type: ClusterIP
  name: loadgenerator
  ports: 
  - port: 8080
    targetPort: 8080

